name: Feature request
description: 改善案を提案する
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 提案内容
    validations:
      required: true
